### ISSUE TITLE
Wiki not Syncing

### ISSUE THREAD

**Issue by TheEnigmo** [weirdgloop/WikiSync#13] opened 2023-12-01 00:57 UTC
### Issue
OSRS Wiki does not sync up currently with my OSRS account; there are numerous tasks in Leagues IV I've completed that are not showing as completed on the wiki when I click "Look up". 

### Resolution attempts

- Attempted to log out and log back in
- Attempted to refresh the OSRS Wiki page
- Restarted browser
- Uninstalled and reinstalled plugin
- After checking off a completed task, I refresh or click "look up" and the same tasks are back to being unhighlighted.

**Comment by leejt** [comment] 2023-12-01 07:47
Hey, can you share your OSRS username? That will help us figure out whether the data is at least making it to the server initially.

**Comment by TheEnigmo** [comment] 2023-12-03 20:12
> Hey, can you share your OSRS username? That will help us figure out whether the data is at least making it to the server initially.

Sure, it's Muzzershet lol.

**Comment by TheEnigmo** [comment] 2023-12-03 21:06
Hey please disregard, I'm an idiot - I forgot I changed my in game name that's why. Thanks for getting back to me!

**Comment by joshi-sh** [comment] 2024-02-23 03:57
I have this same issue.  You can see the issue in the attached screenshot, where it thinks I've completed Lair of Tarn Razorlor but not its prequel Haunted Mine (I've started neither). I did change my user name too, but I didn't see this issue for about a month. Some completed quests (e.g. Ernest the Chicken) show as not completed, and some quests I've started but not completed show as completed (e.g. Troll Romance) 
![wikisync](https://github.com/andmcadams/WikiSync/assets/7287073/7318afb4-6aee-463d-8000-1f4a4a6ccd81)

**Comment by Molecuhl** [comment] 2024-02-23 18:32
I am also running into the above issue (IGN: Molecuhl). Mine start even earlier with the below quests
![Capture](https://github.com/andmcadams/WikiSync/assets/161071596/a28d42b3-60f1-4e11-a594-e5edef5006c3)

**Comment by WaylonJ** [comment] 2024-02-23 20:19
Exact same issue here. The list here doesn't reflect completion accurately. I also changed my name a few months ago. Current name (Ani_ratak)

Quest list (https://oldschool.runescape.wiki/w/Quests/List):
![image](https://github.com/andmcadams/WikiSync/assets/18315347/11eede0f-397d-43f6-9c08-d42318ddbb77)

**Comment by andmcadams** [comment] 2024-02-23 20:36
Hi, these new issues are not the same as the previous issue. The new issue is caused by a change in jagexs cache structure and an automated script we have to build the api. It will be fixed once this pr is deployed https://github.com/weirdgloop/wikisync-api/pull/33

I'm going to close this one for now since the original issue here is not applicable. (Tracking in this issue https://github.com/andmcadams/WikiSync/issues/14 )

**Closed as completed** 2024-02-23 20:37 UTC
